### ISSUE TITLE
[BUG] Forge 1.20.3+ launch error

### ISSUE THREAD

**Issue by TaigoStudio** [Corona-Studio/ProjBobcat#105]
**Describe the bug**
Forge 1.20.3+ launch error

**ProjBobcat Version**
latest

**To Reproduce**
When installing Forge versions 1.20.3 and 1.20.4 and running this version, an error occurs during Bootstrap initialization. There is no such error on other versions 1.20
[01-01-2024.log](https://github.com/Corona-Studio/ProjBobcat/files/13803979/01-01-2024.log)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by laolarou726** [comment]
Currently under investigating.

**Comment by TaigoStudio** [comment]
Well, thanks! Many launchers and cores are faced with the same problem. I will send a link with a discussion and some solution from one of the launchers.
https://github.com/PrismLauncher/PrismLauncher/issues/1934

**Comment by laolarou726** [comment]
> Well, thanks! Many launchers and cores are faced with the same problem. I will send a link with a discussion and some solution from one of the launchers. [PrismLauncher/PrismLauncher#1934](https://github.com/PrismLauncher/PrismLauncher/issues/1934)

The bug has been fixed. Please see the latest commit! PR: #106
