### ISSUE TITLE
发布其他平台的NuGet包

### ISSUE THREAD

**Issue by scgm0** [Corona-Studio/ProjBobcat#151]
比较希望用nuget引入ProjBobcat，不过我系统是arch linux，nuget上的ProjBobcat只包括win api

**Comment by laolarou726** [comment]
> 比较希望用nuget引入ProjBobcat，不过我系统是arch linux，nuget上的包只支持win

Nugent包应该是全平台支持的

**Comment by scgm0** [comment]
> > 比较希望用nuget引入ProjBobcat，不过我系统是arch linux，nuget上的包只支持win
> 
> Nugent包应该是全平台支持的

Nuget是全平台支持，但是ProjBobcat的nuget包只有win的平台api

**Comment by laolarou726** [comment]
> > > 比较希望用nuget引入ProjBobcat，不过我系统是arch linux，nuget上的包只支持win
> > 
> > 
> > Nugent包应该是全平台支持的
> 
> Nuget是全平台支持，但是ProjBobcat的nuget包只有win的平台api

具体是哪个api呢？

**Comment by laolarou726** [comment]
KB上面的初始教程已经过时，我之后会更新，目前下面的初始话代码都是不需要的：

```c#
ServiceHelper.Init();
HttpClientHelper.Init();
```

**Comment by scgm0** [comment]
nuget上的ProjBobcat只有`ProjBobcat.Platforms.Windows`，没有`ProjBobcat.Platforms.Linux`，引入ProjBobcat原始项目的话就有`ProjBobcat.Platforms.Linux`了

**Comment by laolarou726** [comment]
> nuget上的ProjBobcat只有`ProjBobcat.Platforms.Windows`，没有`ProjBobcat.Platforms.Linux`，引入ProjBobcat原始项目的话就有`ProjBobcat.Platforms.Linux`了

谢谢反馈，我后面检查一下

**Comment by yueyinqiu** [comment]
emm 话说生成了 snupkg 为什么最后传上去的是 nupkg ……

**Comment by yueyinqiu** [comment]
很奇怪，我按照 workflow 的指令在本地跑了一遍，没法复现。

**Comment by scgm0** [comment]
> 很奇怪，我按照 workflow 的指令在本地跑了一遍，没法复现。

![图片](https://github.com/Corona-Studio/ProjBobcat/assets/52148221/be4e153a-aea7-4a41-b78b-d66dd115893e)

**Comment by yueyinqiu** [comment]
nueget 拉下来的我这也不行。我是说我重新自己本地 pack 了一下没有这个现象，很奇怪……

**Comment by laolarou726** [comment]
> > 很奇怪，我按照 workflow 的指令在本地跑了一遍，没法复现。
> 
> ![图片](https://private-user-images.githubusercontent.com/52148221/331860540-be4e153a-aea7-4a41-b78b-d66dd115893e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTM3NzEsIm5iZiI6MTcxNzg1MzQ3MSwicGF0aCI6Ii81MjE0ODIyMS8zMzE4NjA1NDAtYmU0ZTE1M2EtYWVhNy00YTQxLWI3OGItZDY2ZGQxMTU4OTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDEzMzExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZTI0ZDNiYzRhNmFkOGY5NTUwMGI3ZDU5MWE3YjkxYWFkZGI0MzdjMWJhNWJjYjc3NzVlZTI2NDEyMGZlYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YqOmamRy5ru2cy9mCtAl_P_AkJYpNwt_k65EfrcgTnY)

最新的 nightly nuget可以吗

**Comment by laolarou726** [comment]
我检查了一下当前项目，目前应该是没有发布平台独占的nuget的，所有api应该都是能够正常被引用的。你现在用的是什么版本呢？

**Comment by yueyinqiu** [comment]
最新版（1.40.0）仍有这个问题

![image](https://github.com/Corona-Studio/ProjBobcat/assets/18749772/ed95aaa6-9b63-4d4b-863d-250c6df74cb0)

**Comment by laolarou726** [comment]
fixed

**Comment by yueyinqiu** [comment]
@laolarou726 i'm wondering why this happens since i can't reproduce that on my machine
