### ISSUE TITLE
A typo in the documentation on the website

### ISSUE THREAD

**Issue by Tartilla-TAIGO** [Corona-Studio/ProjBobcat#157]
![image](https://github.com/Corona-Studio/ProjBobcat/assets/126141594/97e2aa82-a9ea-4134-a7dd-dc2f985ac698)
Page url: https://kb.corona.studio/enUS/projbobcat/installers/fabric.html

The library code uses System.Text.Json. If you use Newtonsoft.JSON, then an error occurs converting Newtonsoft.Json.JsonElement to System.Text.Json.JsonElement.
The line should be like this:
var artifacts = System.Text.Json.JsonSerializer.Deserialize<List<FabricLoaderArtifactModel>>(responseJson);

**Comment by yueyinqiu** [comment]
yes the whole document is outdated. there is no reason to use json.net now.

**Comment by BiDuang** [comment]
> yes the whole document is outdated. actually there is no reason to use json.net now. #54

Yeah, recommand to use .Net's native json package now.

**Comment by laolarou726** [comment]
fixed

**Comment by yueyinqiu** [comment]
??? I failed to find any change here: [https://github.com/Corona-Studio/docs/blob/main/enUS/projbobcat/installers/fabric.md](https://github.com/Corona-Studio/docs/blob/main/enUS/projbobcat/installers/fabric.md)

Have we moved it to a new repo?
