### ISSUE TITLE
建议使用.netstandard作为target而不是netfw46

### ISSUE THREAD

**Issue by ac682** [Corona-Studio/ProjBobcat#22]
本身库除了某个win32调用外其他的都不依赖windows, 完全可以跨平台

**Comment by yueyinqiu** [comment]
llr是屑 @laolarou726

**Comment by yueyinqiu** [comment]
目前新分支refactoring使用.net standard重构/写。

**Comment by ac682** [comment]
> 目前新分支refactoring使用.net standard重构/写。

这个工作我fork的仓库也在做，包括分离接口等等

**Comment by laolarou726** [comment]
我们已经将框架切换至了.netcore app 3.1
