### ISSUE TITLE
将依赖与实现分包以支持第三方扩展包

### ISSUE THREAD

**Issue by d3ara1n** [Corona-Studio/ProjBobcat#23]
ProjBobcat.Interface接口下内容可以分门别类整理到Abstraction包中，从而直接支持基于package reference的扩展。

说到package reference，为什么不用新的项目结构呢，vs创建的项目多了很多无用且累赘的文件和臃肿的.csproj文件

**Comment by yueyinqiu** [comment]
目前有refactoring分支在做这个工作。
其实我早就想分离出一套接口了。但是由于llr这个屑（bushi），所以就鸽了。

**Comment by yueyinqiu** [comment]
好关好关（bushi

**Comment by BiDuang** [comment]
🤓
