### ISSUE TITLE
Using with UAP

### ISSUE THREAD

**Issue by ktheticdev** [Corona-Studio/ProjBobcat#39]
I'm currently unable to use the library in my  UWP app that I'm trying to create. Is there a way to do so?

**Comment by laolarou726** [comment]
Sorry to reply late. However, we don't have any plans to add supports for either UWP or dotNET Framework platform. If you are interested in this project. You can just fork it and try to change the target framework by yourself. Now ProjBobcat can only target to latest dotNET5.
