### ISSUE TITLE
authlib-injector 

### ISSUE THREAD

**Issue by WeiMiao-Xin** [Corona-Studio/ProjBobcat#45]
可以加入authlib-injector外置登录的方法吗？
`https://github.com/yushijinhun/authlib-injector`

**Comment by laolarou726** [comment]
我们暂时不考虑增加authlib的自动下载和部署的功能，这部分代码需要开发着自己实现。但是Projbobcat是支持追加java-agent参数的

**Comment by laolarou726** [comment]
在 AddtionalJvmArguments 里面添加 -javaagent:<JavaAgent的路径>=<JavaAgent的参数>。AddtionalJvmArguments 的类型是 IEnumerable<string>
