### ISSUE TITLE
Windows11下启动出现的问题[BUG]

### ISSUE THREAD

**Issue by WeiMiao-Xin** [Corona-Studio/ProjBobcat#57]
**Describe the bug**
启动器给了管理员权限
内存设置的 512  -  4098

其他设置
-Xms512m
-Xmx4098m
-XX:+UseG1GC
-Dfml.ignoreInvalidMinecraftCertificates=true
-Dfml.ignorePatchDiscrepancies=true
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Dos.name="Windows 10"
-Dos.version=10.0
-Djava.library.path="C:\Program Files\Minecraft-1.16.5\Game\003\versions\1.16.5-forge-36.2.27\natives"
-Dminecraft.launcher.brand=""
-Dminecraft.launcher.version=32

**ProjBobcat Version**
Version 1.8.0

**To Reproduce**
[启动 LOG] - 启动游戏
[游戏 LOG] - Error occurred during initialization of VM
[游戏 LOG] - agent library failed to init: instrument
DONE

**Desktop (please complete the following information):**
 - Windows11
 - Net5.0

**Comment by laolarou726** [comment]
你设置了 JavaAgent 吗

**Comment by WeiMiao-Xin** [comment]
设置了，我用Windows10的电脑下运行是正常的

**Comment by laolarou726** [comment]
麻烦提供一下 java agent 的具体参数

**Comment by WeiMiao-Xin** [comment]
-javaagent:E:\开发\C#\WPF\Minecraft-WiMi\Minecraft-WiMi\bin\Debug\net5.0-windows\Game\003\authlib-injector.jar=https://mc.wimi.ink/api/yggdrasil
-Dauthlibinjector.yggdrasil.prefetched=eyJtZXRhIjp7InNlcnZlck5hbWUiOiJCbGVzc2luZyBTa2luIiwiaW1wbGVtZW50YXRpb25OYW1lIjoiWWdnZHJhc2lsIEFQSSBmb3IgQmxlc3NpbmcgU2tpbiIsImltcGxlbWVudGF0aW9uVmVyc2lvbiI6IjUuMS41IiwibGlua3MiOnsiaG9tZXBhZ2UiOiJodHRwczpcL1wvbWMud2ltaS5pbmsifSwiZmVhdHVyZS5ub25fZW1haWxfbG9naW4iOnRydWV9LCJza2luRG9tYWlucyI6WyJtYy53aW1pLmluayJdLCJzaWduYXR1cmVQdWJsaWNrZXkiOiItLS0tLUJFR0lOIFBVQkxJQyBLRVktLS0tLVxuTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFzdWJvQjVTWDIrY2NBVDc4SjBJSFxuVGIwVzhCdjhScFwvUW9ETFwvOGtFWGFFVk1UbzRkWk5VbURsYzRqXC9oZGxIS0hCMXgzRFJSVlcwbmlrdUlnZm42alxuSDN5ZTM0QUZrV0VrcnFZZ0x4TFhwdUo5MmJDVVd1em82Qnc5N3pHeVBNV0ZtTlUwTUJmUmphQ3EwNFlFYkFqYVxuOEt3Qk1uQkFueGNxZVVWR0JzTG82SjVjR0VBU25CXC8rUkYxTDhjbmdcL3E5b2N3Wm84ZnRXVG94TDBCOHdtaEZLXG5Ra2UwU0huZFloVXJSYTZ4MmpYek4rY09lK2dCMEljVTcrckVEQUFlcWdWNldXZDBoM1lGS05xZllLeTZwVUIyXG5GM3dTNE02NkV5SkMzUCszNU1UeGJcL3JvckRYWlBhcEZPS2Uwc1R5UExLVkhiXC9SZmlrYlwvMzBHTUMwa1VZWEZkXG4rNEsyRml1a1VJbzhreXNLVjBOZ2h5ODZnT1IrcFJ2b3ZEQ3dzbk5WZ0hVRENFVWFKUUQ0aVV4cTdLK2dWSDNVXG5IaEJ5UUxQbXdkQ0FPQWd0bHg1WUhiMlpWaHVwUHNSRkZORjczS0tCR3RWejRwOUFiWFJ6QWk1OTY5YnRLazlJXG54RlE3MmNhM1gwajRVWnFSaHJsXC96Nk0yMVwvZHpaVmZEOUpJaVBJZ01kNHVXXC9aSHZPWTYzQU5hcGtxNzBLc3l5XG5cL1RsMEw2NWwyOG4wK3FhQTZ5UW5aN1VQTmRvbFJSeW9uWkpodzhkTnRmVXpXbHF0XC84TyswMGx2djJPMnVHa05cbkhFazE4Ylo2emdkT2NBZ3VMaEFaNlFNVG9lMXBsaDNlOURUYVEwMUJzeGpDQmZyMTZiUXVaUjF0VTNLOTBXZ2hcbktqcWVEV2UrYWZmODRJOFwvYTh6eG9kOENBd0VBQVE9PVxuLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tXG4ifQ==

**Comment by laolarou726** [comment]
试试将这行改为 -javaagent:"E:\开发\C#\WPF\Minecraft-WiMi\Minecraft-WiMi\bin\Debug\net5.0-windows\Game\003\authlib-injector.jar"=https://mc.wimi.ink/api/yggdrasil

**Comment by laolarou726** [comment]
在路径包含空格时，请使用 "" 将路径包裹起来

**Comment by WeiMiao-Xin** [comment]
谢谢，麻烦你了。
是路径包含空格的问题导致不能启动

**Comment by laolarou726** [comment]
你可以加入我们的官方讨论群：677872263
