### ISSUE TITLE
初学者的一个问题

### ISSUE THREAD

**Issue by akchiji888** [Corona-Studio/ProjBobcat#58]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0103	当前上下文中不存在名称“clientToken”	MCL(Projbobcat)	D:\嘉嘉\8-编程\visual studio编程\MCL(Projbobcat)\MainWindow.xaml.cs	46	活动

**Comment by akchiji888** [comment]
我不太知道using该using什么

**Comment by laolarou726** [comment]
可以参考仓库中的example项目

**Comment by CodingEric** [comment]
请确保已经实例化clientToken对象，如果不了解可以参考exanple项目的结构。
