### ISSUE TITLE
FindJava() 无法返回 JDK16 和 JDK17 的路径

### ISSUE THREAD

**Issue by akchiji888** [Corona-Studio/ProjBobcat#62]
ProjBobcat.Class.Helper.SystemInfoHelper.FindJava()只能返回JRE8的路径，无法返回新版本所使用的JDK16与JDK17的路径

**Comment by CodingEric** [comment]
这是一个已知的问题，并且解决方案也已经有了。不久之后会引入新的java检测方法。

**Comment by laolarou726** [comment]
现在只需要调用 SystemInfoHelper.FindJavaFull() 即可对所有可用磁盘进行全盘搜索 Javaw.exe
