### ISSUE TITLE
[BUG] Doesn't support .NET Framework?

### ISSUE THREAD

**Issue by Slddev** [Corona-Studio/ProjBobcat#63]
**Describe the bug**
I am using .NET Framework 4.8 (Latest) and it fails to install.
```
Could not install package 'ProjBobcat 1.16.0'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**ProjBobcat Version**
1.16.0

**To Reproduce**
1.  Install the package on a project that uses .NET Framework 4.8 via Nuget

**Expected behavior**
Should Install properly.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - IDE: Visual Studio 2022 Community Edition
 - Version: 17.2.3

**Comment by laolarou726** [comment]
Because ProjBobcat is using tons of new language features from .net 6.0. As the result, we are not going to support any of the .NET Framework versions. If you want to use this package, please switch your target to at least .NET 5.0 or above.

**Comment by CodingEric** [comment]
@laolarou726 you'd better update the documentation.

**Comment by laolarou726** [comment]
Just updated the document to make the requirement clear.
