### ISSUE TITLE
关于使用VisualStudio开发时的警告和运行闪退问题

### ISSUE THREAD

**Issue by PowerAngelXD** [Corona-Studio/ProjBobcat#75]
**BUG描述**
在对Nuget上的ProjBobcat包进行了安装且成功后，VS跳出来如下警告：
```
警告	
MSB3270	所生成项目的处理器架构“MSIL”与引用“XXX\ProjBobcat.dll”的处理器架构“AMD64”不匹配。
这种不匹配可能会导致运行时失败。
请考虑通过配置管理器更改您的项目的目标处理器架构，以使您的项目与引用间的处理器架构保持一致，或者为引用关联一个与您的项目的目标处理器架构相符的处理器架构	
```
并且在编译后的运行程序会进行闪退，根据文档的描述：
![image](https://user-images.githubusercontent.com/63438232/216325582-cd948224-6303-4c88-b35e-63c51714c678.png)
并没有在VS的项目属性中找到关于“首选32位”的选项，VS版本为2022

**ProjBobcat 版本**
1.23.1

**Comment by PowerAngelXD** [comment]
没有，但是当我使用WPF-UI库的时候，这个问题又消失了

**Comment by laolarou726** [comment]
> 没有，但是当我使用WPF-UI库的时候，这个问题又消失了

听起来不像是 ProjBobcat 的问题 如何可以的话尽量提供一下崩溃日志或者是堆栈信息

**Comment by laolarou726** [comment]
如果可能的话，请提供复现代码。
