### ISSUE TITLE
采用全新的Linux java寻找办法

### ISSUE THREAD

**Issue by HainanWinter-l** [Corona-Studio/ProjBobcat#76]
使用包管理器安装JDK后，会在`/usr/lib/jvm`或`/usr/lib64/jvm`路径下生成文件。即`/usr/lib/jvm/一个JDK/bin/java`或`/usr/lib64/jvm/一个JDK/bin/java`为java路径。此外，若存在`/usr/lib/jvm/一个JDK/release`或`/usr/lib64/一个JDK/release`文件，也可以通过读取改文件中的`JAVA_VERSION="版本"`来获取java版本。若不存在也可以使用`java -version`来获得版本。**使用Process读取时注意，应该使用`.StandardError.ReadToEnd()`，若使用`.StandardOutput.ReadToEnd()`可能会返回空串**
此外，因为各个发行版提供了不同的默认Java选择方法，`/usr/lib/jvm`或`/usr/lib64/jvm`路径下可能存在软连接文件夹，造成重复选择。
[提供一个我的实现，参考参考](https://github.com/HainanWinter-l/JavaSearcher)

**Comment by laolarou726** [comment]
非常感谢，我将在下一个版本中加入对这个搜索方法的支持

**Comment by laolarou726** [comment]
> 非常感谢，我将在下一个版本中加入对这个搜索方法的支持

目前已经加入了对 macOS 的支持，linux后面会加入

**Comment by laolarou726** [comment]
已完成
