### ISSUE TITLE
How to fix MultiPlayer is disabled?

### ISSUE THREAD

**Issue by TaigoStudio** [Corona-Studio/ProjBobcat#89]
![image](https://github.com/Corona-Studio/ProjBobcat/assets/126141594/3074bd72-852e-46af-b8ae-013f8526462f)
Hi. I use an offline account, but for some reason I can't connect to the servers? What do you specify as arguments to allow entry?

**Comment by imJack6** [comment]
This problem will occur in some versions of 1.16. As far as I know, the solution is as follows
1. Install related repair MOD
2. Start the game after disconnecting the network
3. Join the single player mode first and then exit to the main menu

**Comment by TaigoStudio** [comment]
Okay, thank you
