### ISSUE TITLE
[BUG] Yggdrasil cannot log in, login failed

### ISSUE THREAD

**Issue by imJack6** [Corona-Studio/ProjBobcat#91]
**Describe the bug**
When I use the skin station and need to use the YggdrasilAuthenticator authenticator, when executing `var authResult = await yggdrasilAuthenticator.AuthTaskAsync();`, `result.User` is Null, resulting in `Object reference not set to an instance of an object` , the first exception occurs at `ProjBobcat\DefaultComponent\Authenticator\YggdrasilAuthenticator.cs:line 176`

**ProjBobcat Version**
The latest Master branch of the repository

**To Reproduce**
1.  Initialize the Authenticator
```
            var yggdrasilAuthenticator = new YggdrasilAuthenticator
            {
                AuthServer = [AuthServer],
                Email = [Email],
                LauncherAccountParser = ...,
                Password = [Password]
            };
```
2. Use `var authResult = await yggdrasilAuthenticator.AuthTaskAsync();` to authenticate.
3. Go to `ProjBobcat\DefaultComponent\Authenticator\YggdrasilAuthenticator.cs:line 176` to see the error.

**Expected behavior**
Can login

**Screenshots**
![image](https://github.com/Corona-Studio/ProjBobcat/assets/58357771/c31d1869-18af-4df7-8249-89022e43043c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**
When I checked the source code, I found that the `result.User` at
```
        var profile = new AccountModel
        {
            AccessToken = result.AccessToken,
            AccessTokenExpiresAt = DateTime.Now.AddHours(48),
            EligibleForMigration = false,
            HasMultipleProfiles = profiles.Count > 1,
            Legacy = false,
            LocalId = rUuid,
            Persistent = true,
            RemoteId = result.User.UUID.ToString(),
            Type = "Mojang",
            UserProperites = result.User?.Properties?.ToAuthProperties(profiles).ToArray() ??
                             Array.Empty<AuthPropertyModel>(),
            Username = Email
        };
```
was Null and caused an exception to be thrown.

**Comment by laolarou726** [comment]
fixed
